#if !canImport(ObjectiveC)
import XCTest

extension JWTKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JWTKitTests = [
        ("testECDSAGenerate", testECDSAGenerate),
        ("testECDSAPublicPrivate", testECDSAPublicPrivate),
        ("testExpirationDecoding", testExpirationDecoding),
        ("testExpirationEncoding", testExpirationEncoding),
        ("testExpired", testExpired),
        ("testParse", testParse),
        ("testRSA", testRSA),
        ("testRSASignWithPublic", testRSASignWithPublic),
        ("testSigners", testSigners),
    ]

    static let __allTests__JWKTests = [
        ("testJWKSigner", testJWKSigner)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JWTKitTests.__allTests__JWTKitTests),
        testCase(JWTKitTests.__allTests__JWKTests),
    ]
}
#endif
